services:

  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  odoo:
    image: odoo-custom:19.0.0-prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo_data:/var/lib/odoo

volumes:
  postgres_data:
  odoo_data: